[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/MaCoZu/Python/blob/main/NOTEBOOKS/pandas/00_intro_to_pandas_groupactivity.ipynb)

## Resources
- https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html
- https://macozu.github.io/notes/notes/introduction-to-pandas
- https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf

In [ ]:
import pandas as pd

In [13]:
df = pd.read_csv("https://drive.google.com/uc?id=1GWHKPdxVuqroKoKoB49zOEyfyLAwbzcc",encoding='latin1')

In [15]:
print(df.columns)

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [16]:
df[['Order ID','Customer ID','Product Name','Sales','Profit']]

,Order ID,Customer ID,Product Name,Sales,Profit
0,CA-2013-152156,CG-12520,Bush Somerset Collection Bookcase,261.9600,41.9136
1,CA-2013-152156,CG-12520,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,219.5820
2,CA-2013-138688,DV-13045,Self-Adhesive Address Labels for Typewriters b...,14.6200,6.8714
3,US-2012-108966,SO-20335,Bretford CR4500 Series Slim Rectangular Table,957.5775,-383.0310
4,US-2012-108966,SO-20335,Eldon Fold 'N Roll Cart System,22.3680,2.5164
...,...,...,...,...,...
9989,CA-2011-110422,TB-21400,Ultra Door Pull Handle,25.2480,4.1028
9990,CA-2014-121258,DB-13060,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,15.6332
9991,CA-2014-121258,DB-13060,Aastra 57i VoIP phone,258.5760,19.3932
9992,CA-2014-121258,DB-13060,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,13.3200
9993,CA-2014-119914,CC-12220,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,72.9480

In [20]:
unique_customers= df['Customer ID'].nunique()
print(unique_customers)

793

In [21]:
print(df['Ship Mode'].unique())

['Second Class' 'Standard Class' 'First Class' 'Same Day']

In [28]:
print("Mean:", df['Profit'].mean())
print("Sum:", df['Profit'].sum())
print("90% Quantile:",df['Profit'].quantile(0.90))

Mean: 28.65689630778467
Sum: 286397.0217
90% Quantile: 89.28162000000006

In [30]:
print(df['Category'].value_counts())

Category
Office Supplies    6026
Furniture          2121
Technology         1847
Name: count, dtype: int64

In [33]:
df[df['Customer ID']=='RB-19465']['Customer Name'].unique()

array(['Rick Bensley'], dtype=object)

In [35]:
df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst=True, format='mixed')
df['Ship Date'] = pd.to_datetime(df['Ship Date'], dayfirst=True, format='mixed')
print("Order Dates:", df['Order Date'].min(), "to", df['Order Date'].max())
print("Ship Dates:", df['Ship Date'].min(), "to", df['Ship Date'].max())

Order Dates: 2011-01-04 00:00:00 to 2014-12-31 00:00:00
Ship Dates: 2011-01-08 00:00:00 to 2015-01-06 00:00:00

In [37]:
Order_may_5=df[df['Order Date']=='2014-05-05']

In [38]:
furniture_may_5=df[(df['Order Date']=='2014-05-05')&(df['Category']=='furniture')]
furniture_may_5

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country, City, State, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit]
Index: []

[0 rows x 21 columns]

In [41]:
from numpy import isin
south_dates = df[df['Region'] == 'South']['Order Date']
west_dates = df[df['Region'] == 'West']['Order Date']
matching_days = set(south_dates).intersection(set(west_dates))
order_same_day = df[df['Order Date'].isin(matching_days)]

In [42]:
df.groupby('Region')['Profit'].mean()

Region
Central    17.092709
East       32.135808
South      28.857673
West       33.849032
Name: Profit, dtype: float64

In [43]:
df['Cost']=df['Profit']-df['Sales']
df[['Sales','Profit','Cost']].head()

      Sales    Profit       Cost
0  261.9600   41.9136  -220.0464
1  731.9400  219.5820  -512.3580
2   14.6200    6.8714    -7.7486
3  957.5775 -383.0310 -1340.6085
4   22.3680    2.5164   -19.8516

ANSWER 6: A 90% quantile of 89.28 means that 90% of all orders generated a profit of 89.28 dollars or less.conversely,only 10%of ourmost profitable orders earned more than 89.28 dollars.